### ISSUE TITLE
[CI]レジストリの検討

### ISSUE THREAD

**Issue by shokorep** [aspida/api-types#12]
## サブジェクト
npmのレジストリを
`http://registry.npmjs.org/`
ではなく
`https://npm.pkg.github.com/`
にしたい

## ポイント
* githubにnpmが買収されたことにより、今後はGitHub Package Registryでのpackage公開が主流になると想定されるため、api-typesもgithub package resistry経由で公開したい

## 良い点
* GitHubのプルリクエストから、セキュリティの改良などnpmのパッケージのバージョンの変化をトレース可能になる
* github actionsを用いたCIが楽

## その他
* scoped packageとしてpackageを公開、取得する必要がある

## 懸念点
* パッケージ検索方法の変更
 https://www.npmjs.com/ にはpublishしたpackageは表示されず、https://www.npmjs.com/ 上で検索はできない(レジストリが異なるため)
逆に、githubの左上のsearchboxで検索が可能になる
https://help.github.com/ja/github/searching-for-information-on-github/searching-for-packages#about-searching-for-packages

* 今今、github packages registryのpackageを使うためには
.npmrcファイルでレジストリを定義する必要がある
https://help.github.com/ja/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#installing-a-package
が、githubのレジストリを指定すればgithubのレジストリにパッケージがない場合、npmのレジストリを見にいく仕組みになっている
(買収によって↑このレジストリ定義が必要なくなるのでは？と想定)

**Comment by shokorep** [comment]
実験してみたところレジストリとして、github resistryとnpmjs registry両方利用できそうです。
ひとまず**github registryとnpmjs registryの両方に登録する方針にし、
github registryが主流になってきたらgithub registryのみの更新とする（npmjs registryの方をdeprecatedにする）**
という運営もありではないかと思いました。


上記より、懸念点にあげた点について↓のようになります。
- npmjsで検索できない 
　→npmjsとgithub両方で検索可能
- .npmrcファイルでレジストリ定義が必要
　→npmjsからも依存解決できるようになるため不要

**Comment by maccostar** [comment]
ご提案ありがとうございます。
いただいな内容(直近は両方登録→タイミングを見てgithub registryに集約)でよいと思います。
